### ISSUE TITLE
Include open graph/meta tags to display preview of cool-oer page (https://clixoer.tiss.edu/cool/oer) in social media.

### ISSUE THREAD

**Issue by SadaqatMulla** [CLIxIndia-Dev/clixoer#89]
- [ ] Name to appear: COOL-OER
- [ ] Display initial lines from the "About COOL-OER" description.
- [ ] Display "OER REPOSITORY" image from slider. If needed on the page just keep that one image.

Example of how

**Comment by vighneshmufc** [comment]
![photo6228772460304640719](https://user-images.githubusercontent.com/14256897/101351205-405d6d00-38b6-11eb-90b3-b1d53898b33f.jpg)


Not Fixed.. Doesn't show up on Whatsapp Either

**Comment by yogeshu** [comment]
I have included the tags in the meta-list that need to be tested for each handle

**Comment by VirajUtekar** [comment]
Not fixed, initial lines from the "About COOL-OER" description is not same when sharing on telegram,
on whatsapp only link is been displayed

**Screenshot**
![Screenshot from 2021-09-22 11-27-59](https://user-images.githubusercontent.com/90617515/134290713-62a4acf0-9561-4880-8f56-d2e7fbc5f20d.png)
